errorlog="${HOME}/.xerrors"

[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# Настройки логирования и запуск иксов с чистыми логами
if (cp /dev/null "${errorlog}"); then
  chmod 600 "${errorlog}"
  exec >"${errorlog}" 2>&1
fi

-f ~/.Xresources  && xrdb -merge ~/.Xresources

# disable beep
# setterm -blength 0

# disable screen 
# xset s 300 5

#wmname LG3D
#setxkbmap -layout us,ru -variant -option grp:caps_toggle

exec dbus-launch --sh-syntax --exit-with-session awesome
