#ZSH_THEME="romchi"
#ZSH_THEME="ys"
#ZSH_THEME="xiong-chiamiov"
#ZSH_THEME="tjkirch_mod"
#ZSH_THEME="tjkirch"
ZSH_THEME="takashiyoshida"

CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"

DISABLE_AUTO_UPDATE="false"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
DISABLE_UPDATE_PROMPT="true"

ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="dd/mm/yyyy"
HISTFILE=~/.zhistory
ZSH_CUSTOM=/home/rb/bin/zsh

export ZSH=/home/rb/.zsh
export PATH=$HOME/bin:/usr/local/bin:/opt/openresty/bin:$HOME/lo.work/go/bin:/snap/bin/:$PATH
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
export EDITOR='vim'
export GNUPGHOME='/home/rb/lo.work/RomanBulakh/gpg'
export UPDATE_ZSH_DAYS=1
export SSH_KEY_PATH="~/.ssh/id_rsa"
export QT_GRAPHICSSYSTEM='opengl'
export SSH_ENV="$HOME/.ssh/environment"
export GOPATH="$HOME/lo.work/go"
export GO111MODULE=on
export LS_COLORS='ex=00:su=00:sg=00:ca=00:'

if [[ $(hostname) == "hp.lo" ]]; then
  plugins=(ssh-agent git gitfast)
  if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
  fi
  zstyle :omz:plugins:ssh-agent agent-forwarding on
else
  plugins=()
  if [ ! -z "$SSH_AUTH_SOCK" -a "$SSH_AUTH_SOCK" != "$HOME/.ssh/etoken" ] ; then
    ln -fs "$SSH_AUTH_SOCK" "$HOME/.ssh/etoken"
    export SSH_AUTH_SOCK="$HOME/.ssh/etoken"
  fi
  if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
  fi
fi

if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi

source $ZSH/oh-my-zsh.sh
