ZSH_THEME="romchi"

CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"

DISABLE_AUTO_UPDATE="false"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
DISABLE_UPDATE_PROMPT="true"

ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="dd/mm/yyyy"
HISTFILE=~/.zhistory
ZSH_CUSTOM=/home/rb/bin/zsh

export ZSH=/home/rb/.zsh
export PATH=$HOME/bin:/usr/local/bin:$PATH
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
export EDITOR='vim'
export GNUPGHOME='/home/rb/lo.work/RomanBulakh/gpg'

if [[ $(hostname) == "lenovo" ]]; then
  plugins=(git ssh-agent git-prompt)
  zstyle :omz:plugins:ssh-agent agent-forwarding on
else
  plugins=(git git-prompt)

  if [ ! -z "$SSH_AUTH_SOCK" -a "$SSH_AUTH_SOCK" != "$HOME/.ssh/etoken" ] ; then
    ln -fs "$SSH_AUTH_SOCK" "$HOME/.ssh/etoken"
    export SSH_AUTH_SOCK="$HOME/.ssh/etoken"
  fi
fi

source $ZSH/oh-my-zsh.sh
